# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaveObsids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rave_obs_id', models.TextField(blank=True, db_column='RAVE_OBS_ID', null=True)),
                ('obsdate', models.TextField(blank=True, db_column='Obsdate', null=True)),
                ('fieldname', models.TextField(blank=True, db_column='FieldName', null=True)),
                ('platenumber', models.TextField(blank=True, db_column='PlateNumber', null=True)),
                ('fibernumber', models.TextField(blank=True, db_column='FiberNumber', null=True)),
                ('id_2mass', models.TextField(blank=True, db_column='ID_2MASS', null=True)),
                ('id_denis', models.TextField(blank=True, db_column='ID_DENIS', null=True)),
                ('obs_collection', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'rave_obsids',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
                ('type', models.CharField(choices=[('obs:Observation', 'obs:Observation'), ('obs:Reduction', 'obs:Reduction'), ('obs:Classification', 'obs:Classification'), ('obs:Crossmatch', 'obs:Crossmatch'), ('calc:ChemicalPipeline', 'calc:ChemicalPipeline'), ('calc:Distances', 'calc:Distances'), ('other', 'other')], max_length=128, null=True)),
                ('annotation', models.CharField(blank=True, max_length=1024, null=True)),
                ('startTime', models.DateTimeField(null=True)),
                ('endTime', models.DateTimeField(null=True)),
                ('doculink', models.CharField(blank=True, max_length=512, null=True, verbose_name='documentation link')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
                ('type', models.CharField(choices=[('voprov:Project', 'voprov:Project'), ('prov:Person', 'prov:Person')], max_length=128, null=True)),
                ('annotation', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
                ('type', models.CharField(choices=[('prov:Collection', 'prov:Collection'), ('voprov:dataSet', 'voprov:catalog')], max_length=128, null=True)),
                ('annotation', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(blank=True, max_length=128, null=True)),
                ('dataType', models.CharField(blank=True, max_length=128, null=True)),
                ('storageLocation', models.CharField(blank=True, max_length=1024, null=True, verbose_name='storage location')),
            ],
        ),
        migrations.CreateModel(
            name='HadMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=128, null=True)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provapp.Entity')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='provapp.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Used',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=128, null=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provapp.Activity')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provapp.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='WasAssociatedWith',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=128, null=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provapp.Activity')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provapp.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='WasAttributedTo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=128, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provapp.Agent')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provapp.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='WasDerivedFrom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('generatedEntity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provapp.Entity')),
                ('usedEntity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generatedEntity', to='provapp.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='WasGeneratedBy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=128, null=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provapp.Activity')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provapp.Entity')),
            ],
        ),
    ]
