# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provapp', '0004_entity_rename_status_to_rights'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasInformedBy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('informant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informed', to='provapp.Activity')),
                ('informed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provapp.Activity')),
            ],
        ),
        migrations.RemoveField(
            model_name='hadmember',
            name='role',
        ),
    ]
