# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provapp', '0005_add_wasInformedBy_remove_role_hadMember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFlow',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='provapp.Activity')),
            ],
            bases=('provapp.activity',),
        ),
        migrations.CreateModel(
            name='HadStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activityFlow', to='provapp.Activity')),
                ('activityFlow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provapp.ActivityFlow')),
            ],
        ),
        migrations.AlterField(
            model_name='agent',
            name='annotation',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
