# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provapp', '0008_auto_20170612_0836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ECollection',
            new_name='Collection',
        ),
        migrations.RenameField(
            model_name='hadmember',
            old_name='collection',
            new_name='collectionE',
        ),
        migrations.AlterField(
            model_name='hadmember',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collectionE', to='provapp.Entity'),
        ),
    ]
