# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provapp', '0010_auto_20170612_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hadmember',
            old_name='ecollection',
            new_name='collection',
        ),
    ]
