# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParameterDescription',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('annotation', models.CharField(blank=True, max_length=512, null=True)),
                ('datatype', models.CharField(blank=True, choices=[('vo:boolean', 'vo:boolean'), ('vo:bit', 'vo:bit'), ('vo:unsignedByte', 'vo:unsignedByte'), ('vo:short', 'vo:short'), ('vo:int', 'vo:int'), ('vo:long', 'vo:long'), ('vo:char', 'vo:char'), ('vo:unicodeChar', 'vo:unicodeChar'), ('vo:float', 'vo:float'), ('vo:double', 'vo:double'), ('vo:floatComplex', 'vo:floatComplex'), ('vo:doubleComplex', 'vo:doubleComplex')], max_length=128, null=True)),
                ('xtype', models.CharField(blank=True, choices=[('timestamp', 'timestamp'), ('position', 'position')], max_length=128, null=True)),
                ('unit', models.CharField(blank=True, max_length=128, null=True)),
                ('ucd', models.CharField(blank=True, max_length=128, null=True)),
                ('utype', models.CharField(blank=True, max_length=128, null=True)),
                ('arraysize', models.IntegerField(blank=True, null=True)),
                ('minval', models.CharField(blank=True, max_length=128, null=True)),
                ('maxval', models.CharField(blank=True, max_length=128, null=True)),
                ('options', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='entity',
            name='rights',
            field=models.CharField(blank=True, choices=[('voprov:public', 'voprov:public'), ('voprov:secure', 'voprov:secure'), ('voprov:propriatary', 'voprov:proprietary')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prov_vo.ParameterDescription'),
        ),
    ]
