# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0002_Add_time_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
