# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0003_rename_entity_datatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prov_vo.Activity'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prov_vo.ParameterDescription'),
        ),
    ]
