# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0006_add_useddescription_wasgeneratedbydescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitydescription',
            name='datatype',
            field=models.CharField(blank=True, choices=[('vo:boolean', 'vo:boolean'), ('vo:bit', 'vo:bit'), ('vo:unsignedByte', 'vo:unsignedByte'), ('vo:short', 'vo:short'), ('vo:int', 'vo:int'), ('vo:long', 'vo:long'), ('vo:char', 'vo:char'), ('vo:unicodeChar', 'vo:unicodeChar'), ('vo:float', 'vo:float'), ('vo:double', 'vo:double'), ('vo:floatComplex', 'vo:floatComplex'), ('vo:doubleComplex', 'vo:doubleComplex')], max_length=128, null=True),
        ),
    ]
