# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0006_add_hadstep_activityflow_addblanks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECollection',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prov_vo.Entity')),
            ],
            bases=('prov_vo.entity',),
        ),
    ]
