# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0009_renaming_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hadmember',
            old_name='collectionE',
            new_name='ecollection',
        ),
        migrations.AlterField(
            model_name='hadmember',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecollection', to='prov_vo.Entity'),
        ),
    ]
