# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0011_auto_20170612_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='rights',
            field=models.CharField(blank=True, choices=[('public', 'public'), ('restricted', 'restricted'), ('internal', 'internal')], max_length=128, null=True),
        ),
    ]
