# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0011_auto_20170612_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='VOResource_AccessURL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1024)),
                ('use', models.CharField(choices=[('full', 'full'), ('base', 'base'), ('dir', 'dir')], default='full', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='VOResource_Capability',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=256, null=True)),
                ('standardID', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VOResource_Interface',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='vr:WebBrowser', max_length=256)),
                ('version', models.CharField(blank=True, default='1.0', max_length=256, null=True)),
                ('role', models.CharField(blank=True, max_length=1024, null=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prov_vo.VOResource_Capability')),
            ],
        ),
        migrations.AddField(
            model_name='voresource_accessurl',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prov_vo.VOResource_Interface'),
        ),
    ]
