# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0012_vosimodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityOption',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('available', models.BooleanField(help_text='True if the service is available, else false')),
                ('note', models.CharField(blank=True, help_text='A status message', max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='enabled',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prov_vo.AvailabilityOption'),
        ),
    ]
