# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov_vo', '0012_add_agent_address_entity_rights_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='type',
            field=models.CharField(choices=[('voprov:Organization', 'voprov:Organization'), ('voprov:Individual', 'voprov:Individual')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='rights',
            field=models.CharField(blank=True, choices=[('voprov:public', 'voprov:public'), ('voprov:restricted', 'voprov:restricted'), ('voprov:internal', 'voprov:internal')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[('voprov:Collection', 'voprov:Collection'), ('voprov:Entity', 'voprov:Entity')], max_length=128, null=True),
        ),
    ]
